/**
 * ISO-3166 Country List
 * Common countries for card billing address selection
 */
export const COUNTRIES = [
  'South Africa',
  'Mozambique',
  'Zimbabwe',
  'Zambia',
  'Botswana',
  'Namibia',
  'Angola',
  'Malawi',
  'Tanzania',
  'Kenya',
  'United States',
  'United Kingdom',
  'Canada',
  'Australia',
  'New Zealand',
  'Brazil',
  'Argentina',
  'Chile',
  'Mexico',
  'India',
  'China',
  'Japan',
  'South Korea',
  'Singapore',
  'Hong Kong',
  'United Arab Emirates',
  'Saudi Arabia',
  'Nigeria',
  'Ghana',
  'Egypt',
  'France',
  'Germany',
  'Italy',
  'Spain',
  'Netherlands',
  'Belgium',
  'Switzerland',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Poland',
  'Portugal',
  'Greece',
  'Ireland',
  'Austria',
  'Czech Republic',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Croatia',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Cyprus',
  'Iceland',
  'Liechtenstein',
  'Monaco',
  'San Marino',
  'Vatican City',
  'Andorra',
  'Russia',
  'Ukraine',
  'Belarus',
  'Moldova',
  'Georgia',
  'Armenia',
  'Azerbaijan',
  'Kazakhstan',
  'Uzbekistan',
  'Turkey',
  'Israel',
  'Jordan',
  'Lebanon',
  'Qatar',
  'Kuwait',
  'Bahrain',
  'Oman',
  'Yemen',
  'Iraq',
  'Iran',
  'Afghanistan',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Bhutan',
  'Myanmar',
  'Thailand',
  'Vietnam',
  'Cambodia',
  'Laos',
  'Malaysia',
  'Indonesia',
  'Philippines',
  'Brunei',
  'East Timor',
  'Papua New Guinea',
  'Fiji',
  'New Caledonia',
  'French Polynesia',
  'Mauritius',
  'Seychelles',
  'Madagascar',
  'Reunion',
  'Mayotte',
  'Comoros',
  'Djibouti',
  'Eritrea',
  'Ethiopia',
  'Somalia',
  'Sudan',
  'South Sudan',
  'Chad',
  'Central African Republic',
  'Cameroon',
  'Equatorial Guinea',
  'Gabon',
  'Republic of the Congo',
  'Democratic Republic of the Congo',
  'Rwanda',
  'Burundi',
  'Uganda',
  'South Sudan',
  'Eritrea',
  'Libya',
  'Tunisia',
  'Algeria',
  'Morocco',
  'Western Sahara',
  'Mauritania',
  'Mali',
  'Burkina Faso',
  'Niger',
  'Senegal',
  'Gambia',
  'Guinea-Bissau',
  'Guinea',
  'Sierra Leone',
  'Liberia',
  'Ivory Coast',
  'Togo',
  'Benin',
  'Cape Verde',
  'São Tomé and Príncipe',
  'Lesotho',
  'Eswatini',
] as const

export type Country = typeof COUNTRIES[number]

