/**
 * FX Conversion Request for MozPaga wholesale ZAR flow.
 * App notification of a request, not a bank confirmation or proof of payment.
 */

import * as admin from 'firebase-admin'
import * as fs from 'fs'
import * as path from 'path'
import PDFDocument from 'pdfkit'

const db = admin.firestore()

const DISCLAIMER =
  'This notification records an FX conversion request facilitated through MozPaga. It is not a bank confirmation nor a proof of payment. Generated by MozPaga.'

const SELLER = 'MozPaga'

function assetPath(filename: string): string | null {
  const candidates = [
    path.join(__dirname, '../../assets', filename),
    path.join(process.cwd(), 'assets', filename),
  ]
  return candidates.find((candidate) => fs.existsSync(candidate)) || null
}

function agentAvatarPath(sourceCurrency: 'MZN' | 'ZAR'): string | null {
  return assetPath(sourceCurrency === 'ZAR' ? 'avatar-ariel.png' : 'Brics-girl-blue.png')
}

function drawCircularAvatar(
  doc: PDFKit.PDFDocument,
  imagePath: string,
  x: number,
  y: number,
  size: number
) {
  doc.save()
  doc.circle(x + size / 2, y + size / 2, size / 2).clip()
  doc.image(imagePath, x, y, { width: size, height: size })
  doc.restore()
}

export interface ConversionProofData {
  txId: string
  userId: string
  userHandle: string | null
  counterpartyHandle: string | null
  sourceCurrency: 'MZN' | 'ZAR'
  destinationCurrency: 'MZN' | 'ZAR'
  sourceAmount: number
  destinationAmount: number
  quotedRate: number
  costRate: number
  sellRate: number
  rewardsMzn: number
  status: string
  timestamp: admin.firestore.Timestamp
}

function formatBuyer(data: ConversionProofData): string {
  const named = (data.counterpartyHandle || '').trim().replace(/^[@$]+/, '')
  if (named) return `@${named}`
  return data.sourceCurrency === 'ZAR' ? 'Moz Client' : 'SA Client'
}

function formatTimestamp(timestamp: admin.firestore.Timestamp): string {
  return timestamp.toDate().toLocaleString('en-ZA', {
    timeZone: 'Africa/Johannesburg',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    timeZoneName: 'short',
  })
}

function formatNumber(amount: number): string {
  return Number(amount || 0).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })
}

function formatMzn(amount: number): string {
  return `MT ${formatNumber(amount)}`
}

function formatZar(amount: number): string {
  return `R ${formatNumber(amount)}`
}

function majorFromMinor(minor: unknown): number {
  const n = Number(minor)
  if (!Number.isFinite(n)) return 0
  return Math.round(n) / 100
}

function roundMajor(value: number): number {
  return Math.round(value * 100) / 100
}

export async function getConversionData(txId: string): Promise<ConversionProofData | null> {
  const txSnap = await db.collection('transactions').doc(txId).get()
  if (!txSnap.exists) return null

  const data = txSnap.data()!
  const type = String(data.type || data.transactionType || '')
  if (type !== 'CONVERSION') return null

  const sourceCurrency = data.sourceCurrency === 'ZAR' ? 'ZAR' : 'MZN'
  const destinationCurrency = data.destinationCurrency === 'ZAR' ? 'ZAR' : 'MZN'
  const sourceAmount =
    majorFromMinor(data.sourceAmountMinor) ||
    Number(sourceCurrency === 'MZN' ? data.amountMzn : data.amountZar) ||
    0
  const sellRate = Number(data.sellRateMZNperZAR || 0)
  const costRate = Number(data.costRateMZNperZAR || data.buyRateMZNperZAR || 0)
  const clientDest = majorFromMinor(data.clientDestinationAmountMinor)
  const destinationAmount =
    sourceCurrency === 'ZAR' && sellRate > 0
      ? clientDest || roundMajor(sourceAmount * sellRate) || Number(data.amountMzn || 0)
      : majorFromMinor(data.expectedDestinationAmountMinor) ||
        Number(destinationCurrency === 'MZN' ? data.amountMzn : data.amountZar) ||
        0

  const userSnap = await db.collection('users').doc(String(data.userId || '')).get()
  const userData = userSnap.exists ? userSnap.data()! : {}

  return {
    txId,
    userId: String(data.userId || ''),
    userHandle: userData?.userHandle || userData?.handle || null,
    counterpartyHandle:
      typeof data.counterpartyHandle === 'string' ? data.counterpartyHandle : null,
    sourceCurrency,
    destinationCurrency,
    sourceAmount,
    destinationAmount,
    quotedRate: Number(data.quotedRate || data.fxRateMZNperZAR || 0),
    costRate,
    sellRate,
    rewardsMzn: majorFromMinor(data.rewardsMznMinor),
    status: String(data.instructionStatus || data.status || 'INITIATED'),
    timestamp: data.createdAt || admin.firestore.Timestamp.now(),
  }
}

export function generateConversionProofPdf(data: ConversionProofData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
      })

      const buffers: Buffer[] = []
      doc.on('data', buffers.push.bind(buffers))
      doc.on('end', () => resolve(Buffer.concat(buffers)))
      doc.on('error', reject)

      const isZarSale = data.sourceCurrency === 'ZAR'
      const costRate = data.costRate > 0 ? data.costRate : data.quotedRate
      const sellRate = data.sellRate > 0 ? data.sellRate : data.quotedRate
      const spread = Math.max(0, sellRate - costRate)
      const marginPct = costRate > 0 ? (spread / costRate) * 100 : 0
      const zarSold = isZarSale ? data.sourceAmount : data.destinationAmount
      const mznReceived = isZarSale
        ? data.destinationAmount || roundMajor(zarSold * sellRate)
        : data.sourceAmount
      const costValue = roundMajor(zarSold * costRate)
      const reward = isZarSale
        ? data.rewardsMzn || roundMajor(zarSold * spread)
        : 0

      const logoPath = assetPath('MoZ-logo.png')
      const leftMargin = 50
      let yPos = 48
      if (logoPath) {
        const logoWidth = 88
        doc.image(logoPath, leftMargin, yPos, { width: logoWidth })
        yPos += 58
      }
      doc.fontSize(16).font('Helvetica-Bold').text('FX Conversion Request', leftMargin, yPos, {
        width: 500,
        align: 'left',
      })
      yPos = doc.y + 10

      const headline = isZarSale
        ? `${formatZar(zarSold)} to ${formatMzn(mznReceived)}`
        : `${formatMzn(data.sourceAmount)} to ${formatZar(data.destinationAmount)}`
      doc.fontSize(14).font('Helvetica-Bold').text(headline, leftMargin, yPos, {
        width: 500,
        align: 'left',
      })
      yPos = doc.y + 16

      const lineHeight = 22
      const labelWidth = 220

      const addRow = (label: string, value: string, boldValue = false) => {
        doc.font('Helvetica-Bold').fontSize(11).text(label, leftMargin, yPos, { width: labelWidth })
        doc.font(boldValue ? 'Helvetica-Bold' : 'Helvetica').text(value, leftMargin + labelWidth, yPos, {
          width: 280,
        })
        yPos += lineHeight
      }

      addRow('Direction:', `${data.sourceCurrency} to ${data.destinationCurrency}`)
      addRow('Conversion type:', 'Client sale')
      if (isZarSale) {
        addRow('ZAR sold:', formatZar(zarSold))
        addRow('MZN received:', formatMzn(mznReceived), true)
        addRow('Client rate:', `${sellRate.toFixed(2)} MZN/ZAR`, true)
        addRow('Seller:', SELLER)
        addRow('Buyer:', formatBuyer(data))
        addRow('Asset sold:', 'ZAR')
        addRow('Settlement currency:', 'MZN')
      } else {
        addRow('MZN sold:', formatMzn(data.sourceAmount))
        addRow('ZAR received:', formatZar(data.destinationAmount), true)
        addRow('Client rate:', `${costRate.toFixed(2)} MZN/ZAR`, true)
        addRow('Seller:', SELLER)
        addRow('Buyer:', formatBuyer(data))
        addRow('Asset sold:', 'MZN')
        addRow('Settlement currency:', 'ZAR')
      }

      yPos += 8
      doc.font('Helvetica-Bold').fontSize(12).text('Rate & margin', leftMargin, yPos)
      yPos += lineHeight

      addRow('Source / cost rate:', `${costRate.toFixed(2)} MZN/ZAR`)
      addRow('Client sell rate:', `${sellRate.toFixed(2)} MZN/ZAR`)
      addRow('Spread:', `${spread.toFixed(2)} MZN/ZAR`)
      addRow('Margin on cost:', `${marginPct.toFixed(2)}%`, true)
      addRow('Reward / gross spread:', formatMzn(reward), true)
      if (isZarSale) {
        addRow('Underlying cost value:', formatMzn(costValue))
      }

      yPos += 8
      addRow('Status:', 'Initiated')
      addRow('Transaction ID:', data.txId)
      addRow('Date:', formatTimestamp(data.timestamp))
      if (data.userHandle) addRow('Account:', data.userHandle)

      yPos += lineHeight
      doc.fontSize(10).font('Helvetica').text(DISCLAIMER, leftMargin, yPos, { width: 500, align: 'left' })
      yPos = doc.y + 14
      const avatarPath = agentAvatarPath(data.sourceCurrency)
      if (avatarPath) {
        drawCircularAvatar(doc, avatarPath, leftMargin, yPos, 48)
      }

      doc.end()
    } catch (error) {
      reject(error)
    }
  })
}
